# SITE SETTINGS
title: ESAS
author: ESAS
baseurl: "" # Otherwise GitHub Pages will set this to "/esas"

# SOCIAL PROFILES
social:
  github: ices-tools-dev/esas

# THEME SETTINGS
theme: minima
remote_theme: peterdesmet/petridish@3.0
colors:
  links: "#2b95a0"  # ICES blue
  banner: "#f15d2a" # ICES banner orange
  footer: "#e0e0e0" # ICES footer gray
font_serif: false

# BUILD SETTINGS
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - LICENSE
