# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# SITE SETTINGS
title: ESAS data model
description: European Seabird At Sea (ESAS) data model
author: ESAS
url: "https://inbo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/esas-data-model" # the subpath of your site, e.g. /blog

# SOCIAL PROFILES
email: oscibio@inbo.be
twitter_username: oscibio
github_username: inbo/esas-data-model

# THEME SETTINGS
theme: minima
remote_theme: peterdesmet/petridish
colors:
  links: "#356196"  # INBO blue
  banner: "#c04384" # INBO fuchsia
  footer: "#3c3c3c" # INBO gray

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - LICENSE
